name: Upload to Amazon S3 and Invalidate CDN Cache

on:
  push:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Invalidate Cloud Front cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION }} --paths "/*"
    - name: Deploy static site to S3 bucket
      run: aws s3 sync dist/tasker-front-end s3://${{ secrets.AWS_S3_BUCKET }} --delete
    
  
